config/routes.rb
Rails.application.routes.draw do

  root 'bookmarks#index'

  resources :bookmarks
  get 'bookmarks/:id/jump', to: 'bookmarks#jump', as: :jump_bookmark
  get 'fetch_title', to: 'bookmarks#fetch_title'

  get 'tags', to: 'tags#index', as: 'tags'
  get 'tags/:id', to: 'tags#show', as: 'tag'

end

app/models/bookmark.rb
require 'uri'

class Bookmark < ActiveRecord::Base
  validates_uniqueness_of :url
  validates_presence_of :url, :title
  validates_format_of :url, with: URI::regexp
  validates_numericality_of :clicks, greater_than_or_equal_to: 0

  has_and_belongs_to_many :tags

  paginates_per 10

  def increment
    self.clicks += 1
  end

  def self.search(query)
    if query
      t = Bookmark.arel_table
      @bookmarks = Bookmark.where(t[:title].matches("%#{query}%").or(t[:description].matches("%#{query}%")))
    else
      @bookmarks = Bookmark.all
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :bookmarks

  paginates_per 20

  def self.top(n)
    Tag.joins(:bookmarks).group("tags.id").order("count(tags.id) desc").limit(n)
  end

  def self.destroy_if_empty
    Tag.where(Tag.arel_table[:id].not_in(Tag.joins(:bookmarks).map{|t| t.id })).each do |tag|
      tag.destroy
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

protected

  def json_request?
    request.format.json?
  end

end

app/controllers/bookmarks_controller.rb
require 'open-uri'
require 'timeout'
require 'nokogiri'
require 'addressable/uri'

class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy, :jump]

  # GET /bookmarks
  # GET /bookmarks?q=substring
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.search(params[:q]).order("bookmarks.clicks desc").page(params[:page])
    @tags = Tag.top(3)
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
    gon.available_tags = Tag.all.map(&:name)
  end

  # GET /bookmarks/1/edit
  def edit
    gon.available_tags = Tag.all.map(&:name)
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    @bookmark.tags = param_tags

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        gon.available_tags = Tag.all.map(&:name)
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    @bookmark.tags = param_tags

    respond_to do |format|
      if @bookmark.update(bookmark_params)
        Tag.destroy_if_empty
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    Tag.destroy_if_empty

    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /bookmarks/1/jump
  def jump
    @bookmark.increment

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to Addressable::URI.parse(@bookmark.url).normalize.to_s, status: 302 }
      else
        format.html { redirect_to :back }
      end
    end
  end

  def fetch_title
    url = params[:url]
    @title = nil
    begin
      Timeout.timeout(10) {
        doc = Nokogiri::HTML(open(Addressable::URI.parse(url).normalize.to_s))
        @title = doc.title
      }
    rescue Timeout::Error
      @title = nil
    end
    respond_to do |format|
      format.json { render :get_title }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:url, :title, :description)
    end

    def param_tags
      if params[:item] and params[:item][:tags]
        tags = Tag.all.to_a
        params[:item][:tags].map { |tag_name|
          tags.detect { |t| t.name == tag_name } || Tag.new(name: tag_name)
        }
      else
        []
      end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]
  def index
    @tags = Tag.joins(:bookmarks).select("tags.*, count(bookmarks.id) as bookmarks_count").group("tags.id").order("bookmarks_count desc").page(params[:page])
  end

  def show
    @bookmarks = @tag.bookmarks.page(params[:page])
  end

private

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for @bookmark, :html => { :class => "form-horizontal bookmark" } do |f| %>

  <% if @bookmark.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @bookmark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :url, :class => 'form-control' %>
      <%=f.error_span(:url) %>
    </div>
    <div class="col-lg-2">
      <%= content_tag :span, t("bookmarks.fetch_title", default: "Fetch Title"), id: "fetch_title", class: 'btn btn-info', onclick: 'javascript:fetchTitle();' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
      <%=f.error_span(:title) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
      <%=f.error_span(:description) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tags, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <ul id="tags">
        <% @bookmark.tags.each do |tag| %>
          <li><%= tag.name %></li>
        <% end %>
      </ul>
      <%=f.error_span(:tags) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bookmarks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/bookmarks/_list.html.erb
<table class="table table-striped">
  <% @bookmarks.each do |bookmark| %>
    <tr>
      <td>
        <div>
          <%= link_to bookmark.title, jump_bookmark_path(bookmark), class: "bookmark_title" %>
          <% bookmark.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag), class: "btn btn-default btn-xs" %>
          <% end %>
        </div>
        <div><span class="bookmark_url"><%= fa_icon :link, text: truncate(bookmark.url, length: 50, separator: "/") %> &nbsp; (<%= bookmark.clicks %> clicks)</span></div>
        <div><span class="bookmark_description"><%= truncate(bookmark.description, length: 50) do %><%= link_to '詳細を見る', bookmark_path(bookmark) %><% end %></span></div>
      </td>
      <td>
        <%= link_to fa_icon(:edit, text: t('.edit', :default => t("helpers.links.edit"))),
                    edit_bookmark_path(bookmark), :class => 'btn btn-default btn-xs' %>
        <%= link_to fa_icon(:close, text: t('.destroy', :default => t("helpers.links.destroy"))),
                    bookmark_path(bookmark),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger btn-xs' %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @bookmarks %>

app/views/bookmarks/edit.html.erb
<%- model_class = Bookmark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookmarks/index.html.erb
<%- model_class = Bookmark -%>
<div class="col-sm-9">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <small><%= link_to t('.new', :default => t("helpers.links.new")),
                new_bookmark_path,
                :class => 'btn btn-primary' %></small></h1>
  </div>


  <%= render partial: "list" %>


</div>
<div class="col-sm-3">
  <div class="well sidebar-nav">
    <h3><%= t "tags.top_tags", n: @tags.length, default: "Top #{@tags.length} tags" %></h3>
    <ul class="nav nav-list">
      <% @tags.each do |tag| %>
        <li><%= link_to tag.name, tag_path(tag) %></li>
      <% end %>
    </ul>
  </div><!--/.well -->
</div>

app/views/bookmarks/new.html.erb
<%- model_class = Bookmark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookmarks/show.html.erb
<%- model_class = Bookmark -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @bookmark.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @bookmark.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= simple_format @bookmark.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:clicks) %>:</strong></dt>
  <dd><%= @bookmark.clicks %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd>
    <% @bookmark.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag), class: "btn btn-default btn-xs" %>
    <% end %>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bookmarks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bookmark_path(@bookmark), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bookmark_path(@bookmark),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SimpleBookmarker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= include_gon %>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SimpleBookmarker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to t("navbar.bookmarks", default: "Bookmarks"), bookmarks_path  %></li>
            <li><%= link_to t("navbar.tags", default: "Tags"), tags_path  %></li>
          </ul>
          <%= form_tag(bookmarks_path, method: :get, class: "navbar-form navbar-right", role: "search") do %>
            <div class="form-group">
              <%= text_field_tag 'q', @query, class: "form-control", placeholder: t("bookmarks.search.placeholder", default: "Search bookmark"), size: 50 %>
              <%= submit_tag t("bookmarks.search.button", default: "Search"), class: "btn btn-default" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/tags/index.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= t "tag.bookmark_count", default: "Bookmark Count" %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.name, tag_path(tag) %></td>
        <td><%= tag.bookmarks_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/show.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%= t '.title', tag: @tag.name , default: model_class.model_name.human.titleize %></h1>
</div>

<%= render partial: "bookmarks/list" %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tags_path, :class => 'btn btn-default'  %>